apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ include "reliza-watcher.fullname" . }}-{{ .Release.Namespace }}-crb
    app.kubernetes.io/part-of: {{ include "reliza-watcher.fullname" . }}
  name: {{ include "reliza-watcher.fullname" . }}-{{ .Release.Namespace }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "reliza-watcher.fullname" . }}-{{ .Release.Namespace }}-cr
subjects:
- kind: ServiceAccount
  name: {{ include "reliza-watcher.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}