apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "reliza-watcher.fullname" . }}-cm
data:
  namespace: {{ .Values.namespace }}
  sender: {{.Values.sender}}