{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ include "reliza-watcher.fullname" . }}-sa
  labels:
    {{- include "reliza-watcher.labels" . | nindent 4 }}
{{- end }}
