apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: helm-reliza-sa
    app.kubernetes.io/part-of: helm-reliza
  name: helm-reliza-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helm-reliza-cr
  name: helm-reliza-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-update-data-volume
  labels:
    type: helm-cron-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/helm-upgrade-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-update-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helm-reliza-cron
  labels:
    run: helmcron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          serviceAccount: helm-reliza-sa
          containers:
          - command: ['/bin/sh', '-c', 'cp /apps/script/helm.sh /apps/ && chmod 0700 /apps/helm.sh && /apps/helm.sh $RELIZA_API_ID $RELIZA_API_KEY $RELIZA_HUB_PROJECT_ID $BASE_VALUES_FILE $HELM_RELEASE_NAME $NAMESPACE_TO_DEPLOY $HELM_REPO_LOGIN $HELM_REPO_PASS']
#          - command: ['sleep', '3000']
            image: relizaio/helm-reliza-cli
            name: helmtest
            resources: {}
            env:
            - name: RELIZA_API_ID
              valueFrom:
                secretKeyRef:
                  name: helm-reliza-cd-credentials
                  key: reliza-api-id
            - name: RELIZA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: helm-reliza-cd-credentials
                  key: reliza-api-key
            - name: RELIZA_HUB_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: helm-reliza-cd-credentials
                  key: reliza-project-id
            - name: BASE_VALUES_FILE
              valueFrom:
                configMapKeyRef:
                  name: helm-reliza-cd-configmap
                  key: base-values-file
            - name: HELM_RELEASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: helm-reliza-cd-configmap
                  key: helm-release-name
            - name: NAMESPACE_TO_DEPLOY
              valueFrom:
                configMapKeyRef:
                  name: helm-reliza-cd-configmap
                  key: namespace
            - name: HELM_REPO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: helm-reliza-cd-credentials
                  key: helm-login
            - name: HELM_REPO_PASS
              valueFrom:
                secretKeyRef:
                  name: helm-reliza-cd-credentials
                  key: helm-pass
            - name: RELIZA_HUB_URI
              valueFrom:
                configMapKeyRef:
                  name: helm-reliza-cd-configmap
                  key: RELIZA_HUB_URI
            volumeMounts:
            - mountPath: "/apps/script"
              name: helm-shell-script
            - mountPath: "/apps/work-values"
              name: helm-update-data
          volumes:
            - name: helm-shell-script
              configMap:
                name: helm-shell-script
            - name: helm-update-data
              persistentVolumeClaim:
                claimName: helm-update-data
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
