apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: reliza-client-pod-watcher
    app.kubernetes.io/part-of: reliza-client
  name: reliza-client-pod-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reliza-client-pod-watcher-role
  name: reliza-client-pod-watcher-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: reliza-client-pod-watcher-binding
    app.kubernetes.io/part-of: reliza-client
  name: reliza-client-pod-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reliza-client-pod-watcher-role
subjects:
- kind: ServiceAccount
  name: reliza-client-pod-watcher
  namespace: reliza-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: reliza-client-watcher-deployment
    app.kubernetes.io/part-of: reliza-client
  name: reliza-client-watcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reliza-client-watcher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reliza-client-watcher
    spec:
      containers:
      - name: reliza-client-watcher
        image: relizaio/kubectl-reliza-client
        imagePullPolicy: Always
        env:
        - name: HUB_URI
          value: https://app.relizahub.com
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: reliza-client-configmap
              key: namespace
        - name: SENDER_ID
          valueFrom:
            configMapKeyRef:
              name: reliza-client-configmap
              key: sender
        - name: RELIZA_API_ID
          valueFrom:
            secretKeyRef:
              name: reliza-client-api-key
              key: reliza-api-id
        - name: RELIZA_API_KEY
          valueFrom:
            secretKeyRef:
              name: reliza-client-api-key
              key: reliza-api-key
      serviceAccountName: reliza-client-pod-watcher